version: 2
updates:
  - package-ecosystem: "maven"  # Specifies the package manager (Maven in this case)
    directory: "/"               # The directory where your pom.xml file is located
    schedule:
      interval: "daily"         # Frequency of updates, can be "daily", "weekly", or "monthly"
    commit-message:
      prefix: "deps"             # Prefix for commit message
    versioning-strategy: "increase"  # Options: "increase", "lockfile-only", "auto"
