name: submit-dependency-snapshot

on:
  workflow_run:
    workflows: ['run-build-and-generate-dependency-snapshot']
    types: [completed]

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve dependency graph artifact and submit
      uses: gradle/gradle-build-action@v2
      with:
        dependency-graph: download-and-submit